/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ObexAgentAdaptor -a obexagent.h:obexagent.cpp agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OBEXAGENT_H_QDBUSXML2CPP
#define OBEXAGENT_H_QDBUSXML2CPP

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.bluez.obex.Agent
 */
class ObexAgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bluez.obex.Agent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bluez.obex.Agent\">\n"
"    <method name=\"Release\"/>\n"
"    <method name=\"Progress\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"t\" name=\"transferred\"/>\n"
"    </method>\n"
"    <method name=\"Complete\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"Error\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"error\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ObexAgentAdaptor(QObject *parent);
    virtual ~ObexAgentAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Complete(const QDBusObjectPath &path);
    void Error(const QDBusObjectPath &path, const QString &error);
    void Progress(const QDBusObjectPath &path, qulonglong transferred);
    void Release();
Q_SIGNALS: // SIGNALS
};

#endif
